import {StyleSheet} from 'react-native';
import {COLORS} from '../../constants/Colors';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.primary,
  },
  header: {
    height: 150,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: COLORS.primary,
    paddingHorizontal: 20,
  },
  headerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  headerContainer: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  nameContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    maxWidth: '85%',
  },
  title: {
    color: COLORS.dark,
    fontFamily: 'LeagueSpartan-Bold',
    fontSize: 20,
  },
  icon: {
    width: 5,
    height: 5,
    backgroundColor: COLORS.orangeBase,
    borderRadius: 5,
  },
  imageContainer: {
    backgroundColor: COLORS.orangeBase,
    width: 22,
    height: 22,
    borderRadius: 50,
    alignItems: 'center',
    justifyContent: 'center',
  },
  image: {
    width: 10,
    height: 10,
    resizeMode: 'contain',
  },
  ratingContainer: {
    position: 'absolute',
    left: 10,
    bottom: 10,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    backgroundColor: COLORS.orangeBase,
    borderRadius: 30,
    paddingHorizontal: 5,
    marginLeft: 10,
  },
  rating: {
    fontFamily: 'LeagueSpartan-Regular',
    fontSize: 12,
    color: COLORS.lightWhite,
  },
  star: {
    width: 9,
    height: 9,
    resizeMode: 'contain',
  },
  scrollContainer: {
    flexGrow: 1,
  },
  foodImageContainer: {
    width: '100%',
    height: 200,
    position: 'relative',
  },
  foodImage: {
    borderRadius: 36,
    width: '100%',
    height: '100%',
    resizeMode: 'cover',
  },
  badgeContainer: {
    position: 'absolute',
    top: -20,
    right: -20,
    alignItems: 'center',
    justifyContent: 'center',
  },
  badge: {
    width: 71,
    height: 71,
    resizeMode: 'contain',
  },
  badgeText: {
    position: 'absolute',
    textAlign: 'center',
    fontFamily: 'LeagueSpartan-Bold',
    fontSize: 16,
    lineHeight: 16,
    color: COLORS.lightWhite,
  },
  priceContainer: {
    marginTop: 30,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderBottomColor: COLORS.lightOrange,
    borderBottomWidth: 1,
    borderTopColor: COLORS.lightOrange,
    borderTopWidth: 1,
    paddingVertical: 15,
  },
  priceSection: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  price: {
    fontFamily: 'LeagueSpartan-Bold',
    fontSize: 24,
    lineHeight: 26,
    color: COLORS.orangeBase,
  },
  oldPrice: {
    fontFamily: 'LeagueSpartan-Regular',
    fontSize: 14,
    lineHeight: 14,
    color: COLORS.primary,
    textDecorationLine: 'line-through',
    textDecorationColor: COLORS.orangeBase,
  },
  quantityContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  quantityButton: {
    backgroundColor: COLORS.orangeBase,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
    height: 26,
    width: 26,
  },
  quantityIcon: {
    width: 10,
    height: 10,
    resizeMode: 'contain',
  },
  quantityText: {
    fontFamily: 'LeagueSpartan-Regular',
    fontSize: 24,
    lineHeight: 22,
    color: COLORS.dark,
  },
  detailContainer: {
    gap: 30,
  },
  descriptionContainer: {
    marginTop: 18,
    gap: 7,
  },
  mainTitle: {
    fontFamily: 'LeagueSpartan-Medium',
    fontSize: 20,
    lineHeight: 18,
    color: COLORS.dark,
  },
  description: {
    fontFamily: 'LeagueSpartan-Light',
    fontSize: 16,
    lineHeight: 15,
    color: COLORS.dark,
  },
  portionContainer: {
    gap: 15,
  },
  portionTitle: {
    fontFamily: 'LeagueSpartan-Medium',
    fontSize: 20,
    lineHeight: 18,
    color: COLORS.dark,
  },
  portionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
  },
  portionName: {
    fontFamily: 'LeagueSpartan-Light',
    fontSize: 14,
    color: COLORS.dark,
    marginBottom: 2,
    maxWidth: '60%',
  },
  dottedDivider: {
    flexGrow: 1,
    height: 1,
    borderBottomColor: COLORS.lightOrange,
    borderBottomWidth: 1,
    borderStyle: 'dotted',
    marginHorizontal: 8,
  },
  portionPrice: {
    fontFamily: 'LeagueSpartan-Light',
    fontSize: 12,
    color: COLORS.dark,
  },
  checkboxContainer: {
    width: 20,
    height: 20,
    borderRadius: 10,
    borderColor: COLORS.orangeBase,
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  checkboxInner: {
    width: 12,
    height: 12,
    borderRadius: 10,
    borderColor: COLORS.orangeBase,
    borderWidth: 1,
  },
  buttonContainer: {
    marginTop: 30,
    alignItems: 'center',
    justifyContent: 'center',
  },
  button: {
    width: 180,
    height: 35,
    borderRadius: 40,
    backgroundColor: COLORS.orangeBase,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 14,
  },
  buttonImage: {
    width: 16,
    height: 16,
    resizeMode: 'contain',
  },
  buttonText: {
    fontFamily: 'LeagueSpartan-Medium',
    fontSize: 20,
    lineHeight: 22,
    color: COLORS.light,
  },
});

export default styles;
